name: Java CI with Gradle
on:
  push:
    branches:
      - "release/**"
      - "main"
      - "develop"

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: source/did-blockchain-sdk-server
    permissions:
      contents: write
      repository-projects: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Gradle Wrapper
        run: gradle clean build

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-${{ github.sha }}
          path: |
            source/did-blockchain-sdk-server/build/libs/*.jar